require("dotenv").config();
const {
  checkUserExists,
  verifyOtp,
  insertOtp,
} = require("../models/employeeOtpModel");
const { sendEmail } = require("../services/emailService");
const path = require("path");

const generateOtp = async (req, res) => {
  try {
    const payload = req.body;
    console.log("📩 Coming from frontend:", payload);

    // 1️⃣ Validate email format
    if (!payload.EMAIL || !/\S+@\S+\.\S+/.test(payload.EMAIL)) {
      return res.status(400).json({ error: "Valid email is required" });
    }

    // 2️⃣ Check if user exists
    const exists = await checkUserExists(payload.EMAIL);
    if (!exists) {
      return res.status(404).json({ error: "Email not registered" });
    }

    // 3️⃣ Insert OTP via DB procedure
    const dbResult = await insertOtp(payload);
    const otp = dbResult?.OTP;
    if (!otp) {
      return res.status(500).json({ error: "OTP not generated by DB" });
    }

    const expiryMinutes = process.env.OTP_EXPIRY || 5;

    // 4️⃣ Prepare email content (rich template)
    const subject = "Your OTP for Secure Verification – Samskruthi Airlines";
    const text = `Dear Customer,

Your One-Time Password (OTP) is: ${otp}

Please enter this code to complete your verification.
This OTP is valid for ${expiryMinutes} minutes.
For your security, do not share this code with anyone.

If you did not request this OTP, please ignore this message.

Best regards,
Samskruthi Airlines – Security Team
(no-reply@samskruthi.com)`;

    const html = `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <div style="text-align:center; margin-bottom: 20px;">
          <img src="cid:airlineslogo" alt="Samskruthi Airlines" style="width: 150px;"/>
        </div>
        <h2 style="color: #000; margin-bottom: 10px;">Samskruthi Airlines</h2>
        <p>Dear Customer,</p>
        <p>Your One-Time Password (OTP) is:</p>
        <p style="font-size: 20px; font-weight: bold; color: #000; background:#f4f4f4; padding:10px; display:inline-block; border-radius:6px;">
          ${otp}
        </p>
        <p>Please enter this code to complete your verification.</p>
        <p>This OTP is valid for <b style="color: #000;">${expiryMinutes} minutes</b>.</p>
        <p>For your security, do not share this code with anyone.</p>
        <p>If you did not request this OTP, please ignore this message.</p>
        <br/>
        <p>Best regards,</p>
        <p><strong>Samskruthi Airlines – Security Team</strong></p>
        <hr/>
        <footer style="font-size:12px; color:#777; text-align:center;">
          This is an automated message. Please do not reply.<br/>
          Contact us at <a href="mailto:info@samskruthi.com">info@samskruthi.com</a>
        </footer>
      </div>
    `;

    // 5️⃣ Send email
    await sendEmail({
      from: '"Samskruthi Airlines" <no-reply@samskruthi.com>',
      to: payload.EMAIL,
      subject,
      text,
      html,
      attachments: [
        {
          filename: "airlineLogo.png",
          path: path.join(__dirname, "../assets/airlineLogo.png"),
          cid: "airlineslogo", // used in HTML <img src="cid:airlineslogo">
        },
      ],
    });

    // 6️⃣ Send response (return OTP only in dev mode)
    if (process.env.NODE_ENV === "development") {
      return res
        .status(200)
        .json({ success: true, message: "OTP sent successfully", otp });
    }

    return res
      .status(200)
      .json({ success: true, message: "OTP sent successfully" });
  } catch (err) {
    console.error("❌ Error in generateOtp:", err);
    return res
      .status(500)
      .json({ error: "Request failed", details: err.message });
  }
};

const validateOtp = async (req, res) => {
  try {
    const { otp } = req.query;
    if (!otp) {
      return res
        .status(400)
        .json({ success: false, message: "OTP is required" });
    }

    const parsedData = await verifyOtp(otp);
    if (!parsedData) {
      return res
        .status(401)
        .json({ success: false, isValid: 0, message: "Invalid OTP" });
    }

    if (Number(parsedData.IsValid) === 1) {
      return res
        .status(200)
        .json({ success: true, data: parsedData, isValid: 1 });
    }

    return res
      .status(401)
      .json({ success: false, isValid: 0, message: "Invalid OTP" });
  } catch (err) {
    console.error("❌ Error in validateOtp:", err);
    return res
      .status(500)
      .json({ success: false, error: "Database query failed" });
  }
};

module.exports = { generateOtp, validateOtp };
